mongo.inventory.uri = ENC(ixlq2jsAPUc5AxMwEXHjLbN9DVFtvVtKSUvzdTT7/2Li/McZutO/0+Z7yct3v4ORzgZRfUYoTAtBtksVaUk9Pza/BZCdV0J0tgG41vt/udSq6O7Bvl1dJg==)
mongo.inventory.database = heroku_app20901983

rabbitmq.host = rabbitmq.sellonall.com
rabbitmq.rx.port = 5672
rabbitmq.tx.port = 5672
rabbitmq.username = user
rabbitmq.password = ENC(nkvU74/e9OtBVxTHG1hvPrc2nER4sNF0)
rabbitmq.virtualHost = messages

amazonmq.host = rabbitmq.sellonall.com
amazonmq.rx.port = 5672
amazonmq.tx.port = 5672
amazonmq.username = user
amazonmq.password = ENC(nkvU74/e9OtBVxTHG1hvPrc2nER4sNF0)
amazonmq.virtualHost = messages

ebaymq.host = rabbitmq.sellonall.com
ebaymq.rx.port = 5672
ebaymq.tx.port = 5672
ebaymq.username = user
ebaymq.password = ENC(nkvU74/e9OtBVxTHG1hvPrc2nER4sNF0)
ebaymq.virtualHost = messages

wishmq.host = rabbitmq.sellonall.com
wishmq.rx.port = 5672
wishmq.tx.port = 5672
wishmq.username = user
wishmq.password = ENC(nkvU74/e9OtBVxTHG1hvPrc2nER4sNF0)
wishmq.virtualHost = messages

shopifymq.host = rabbitmq.sellonall.com
shopifymq.rx.port = 5672
shopifymq.tx.port = 5672
shopifymq.username = user
shopifymq.password = ENC(nkvU74/e9OtBVxTHG1hvPrc2nER4sNF0)
shopifymq.virtualHost = messages

shopeemq.host = rabbitmq.sellonall.com
shopeemq.rx.port = 5672
shopeemq.tx.port = 5672
shopeemq.username = user
shopeemq.password = ENC(nkvU74/e9OtBVxTHG1hvPrc2nER4sNF0)
shopeemq.virtualHost = messages

sellinallmq.host = rabbitmq.sellonall.com
sellinallmq.rx.port = 5672
sellinallmq.tx.port = 5672
sellinallmq.username = user
sellinallmq.password = ENC(nkvU74/e9OtBVxTHG1hvPrc2nER4sNF0)
sellinallmq.virtualHost = messages

flipkartmq.host = rabbitmq.sellonall.com
flipkartmq.rx.port = 5672
flipkartmq.tx.port = 5672
flipkartmq.username = user
flipkartmq.password = ENC(nkvU74/e9OtBVxTHG1hvPrc2nER4sNF0)
flipkartmq.virtualHost = messages

shopcluesmq.host = rabbitmq.sellonall.com
shopcluesmq.rx.port = 5672
shopcluesmq.tx.port = 5672
shopcluesmq.username = user
shopcluesmq.password = ENC(nkvU74/e9OtBVxTHG1hvPrc2nER4sNF0)
shopcluesmq.virtualHost = messages

etsymq.host = rabbitmq.sellonall.com
etsymq.rx.port = 5672
etsymq.tx.port = 5672
etsymq.username = user
etsymq.password = ENC(nkvU74/e9OtBVxTHG1hvPrc2nER4sNF0)
etsymq.virtualHost = messages

feemanagementmq.host = rabbitmq.sellonall.com
feemanagementmq.rx.port = 5672
feemanagementmq.tx.port = 5672
feemanagementmq.username = user
feemanagementmq.password = ENC(nkvU74/e9OtBVxTHG1hvPrc2nER4sNF0)
feemanagementmq.virtualHost = messages

#userMessagingServer Server URL
userMessaging.host = rabbitmq.sellonall.com
userMessaging.rx.port = 5672
userMessaging.tx.port = 5672
userMessaging.username = user
userMessaging.password = ENC(nkvU74/e9OtBVxTHG1hvPrc2nER4sNF0)
userMessaging.virtualHost = messages

batchProcessor.host = rabbitmq.sellonall.com
batchProcessor.tx.port = 5672
batchProcessor.rx.port = 5672
batchProcessor.username = user
batchProcessor.password = ENC(nkvU74/e9OtBVxTHG1hvPrc2nER4sNF0)
batchProcessor.virtualHost = messages

qoo10mq.host = rabbitmq.sellonall.com
qoo10mq.rx.port = 5672
qoo10mq.tx.port = 5672
qoo10mq.username = user
qoo10mq.password = ENC(nkvU74/e9OtBVxTHG1hvPrc2nER4sNF0)
qoo10mq.virtualHost = messages

lazada.host = rabbitmq.sellonall.com
lazada.rx.port = 5672
lazada.tx.port = 5672
lazada.username = user
lazada.password = ENC(nkvU74/e9OtBVxTHG1hvPrc2nER4sNF0)
lazada.virtualHost = messages

quickBooks.host = rabbitmq.sellonall.com
quickBooks.rx.port = 5672
quickBooks.tx.port = 5672
quickBooks.username = user
quickBooks.password = ENC(nkvU74/e9OtBVxTHG1hvPrc2nER4sNF0)
quickBooks.virtualHost = messages

ninjaVan.host = rabbitmq.sellonall.com
ninjaVan.rx.port = 5672
ninjaVan.tx.port = 5672
ninjaVan.username = user
ninjaVan.password = ENC(nkvU74/e9OtBVxTHG1hvPrc2nER4sNF0)
ninjaVan.virtualHost = messages

#Buyer Management
buyer.host = rabbitmq.sellonall.com
buyer.tx.port = 5672
buyer.username = user
buyer.password = ENC(nkvU74/e9OtBVxTHG1hvPrc2nER4sNF0)
buyer.virtualHost = messages

infor.host = rabbitmq.sellonall.com
infor.rx.port = 5672
infor.tx.port = 5672
infor.username = user
infor.password = ENC(nkvU74/e9OtBVxTHG1hvPrc2nER4sNF0)
infor.virtualHost = messages

magentomq.host = rabbitmq.sellonall.com
magentomq.rx.port = 5672
magentomq.tx.port = 5672
magentomq.username = user
magentomq.password = ENC(nkvU74/e9OtBVxTHG1hvPrc2nER4sNF0)
magentomq.virtualHost = messages

elevenStreetmq.host = rabbitmq.sellonall.com
elevenStreetmq.rx.port = 5672
elevenStreetmq.tx.port = 5672
elevenStreetmq.username = user
elevenStreetmq.password = ENC(nkvU74/e9OtBVxTHG1hvPrc2nER4sNF0)
elevenStreetmq.virtualHost = messages

jdmq.host = rabbitmq.sellonall.com
jdmq.rx.port = 5672
jdmq.tx.port = 5672
jdmq.username = user
jdmq.password = ENC(nkvU74/e9OtBVxTHG1hvPrc2nER4sNF0)
jdmq.virtualHost = messages