#Using Mudra Token get Facebook Long Token
FbTokenExchangeUri=ENC(4nKwYhD6+rmZq7yRAtNjAYeSPi7uVNVklANFWVkHzBIukq8Y78skzGMG3qM2ThU02/ixq5rzE5YBk0O4Tqqb1RKW7NhgQ31YboqlKd0C1dDXEintJvwXKwAKL9QqYnuwpC4cMgZ6KSsgNPSLHZ63ZJ6NSD3wKQJIAXjTa3fG6lDZX/Zkm8GuNCUIYw+tExqN77bIrm98I7RizhlAcpkz+hgQdr8Cb37oh3Ek902bw9w=)

orderConfigDBURI=ENC(1XAasA4r4ZF8LkLtbDYh4P6hpRJ7+CqWM9iEb/ClFjVueVNOlMKO72NnpnnYyJfI+XtiCeS1mqpc9dmIL41yDffW1U9tLd0PxfU8gCR8APKEdrG9ZnDunoYbDhI7ZNMirBfbkoi8JNZp7f6Z1XMjLg==)
orderConfigDBName =orders

# User And Auth Collection Details 
userConfigDBURI=ENC(9e8Ff/WRLu1nIib1tU9zCZeGPxtRn3F8RLTlfjPUEHtvkrVAAI6AChGHaCXkiskXPXXP+3lsess28SCcm9w5xvSqYlsz0a824zqHF/589Rwoo1EpzqmEzcazj57PYrdOP99HbpKRIFsdZerLmEGe7Q==)
userConfigDBName=account

# Inventory Collection Details 
inventoryConfigDBURI=ENC(fsgXDZNbnl1H2uXGy2tiwR2NLY5ag3gBDnsL/QFw9A7A1DJQYhHQCzXjaqg4+geICVCoVJwHkssMYbcFJAnlrHZWBI3DAN0ZoyAhM8U70Hoxfq8Q54tVST5beDiGF5HNpJImoesG5/Wg/phd2eUhMQ==)
inventoryConfigDBName =inventory

#image URI
uploadImageUri=http://dev.sellonall.com/uploads/

#Notification Email URL
SIAOrderPageURL=http://gandeevam.sellonall.com/Dash/#orders-sold?id=

#Accounting channels
SIAAccountingChannels = quickBooks

#feeManagementServer exchange URL
SIAfeeManagementServerURL = https://staging-feemanagement.herokuapp.com/services

#inventory Endpoint
SIAInventoryManagementServerURL = https://stage-inventorymanagement.sellinall.com/services

warehouses = satsaco

#need to remove this flag once whatsApp enabled in SIA
whatsAppEnabled = false

#memcached
MemcachedCloudUsername = memcached-app42013129
MemcachedCloudPassword = ENC(n8yhw55WMyAaXVNg5jGU1zvfUHHnwElfXTAFuGAl2v0=)
MemcachedCloudServers = pub-memcache-15847.us-east-1-2.5.ec2.garantiadata.com:15847

docUploadPath = http://images.sellonall.com/uploads/

#Finopsserv
SIAFinopsServerURL = https://stage-finopsserv.sellinall.com/services

#Maatram integrated ShippingCarrier
maatramIntegratedShippingCarrier = singPost-jtExpress-aramexShipping

#Maatram integrated WMS
maatramIntegratedWms = aramex-ych-SiAWMS-customWMS

#Maatram integrated ERP
maatramIntegratedErp = netSuite-vend-odoo-eccang-sap

#Maatram integrated OMS
maatramIntegratedOms = omsPro

#Maatram Bridge integrated Servers
maatramBridgeIntegratedServers = ych-eccang-sap-customWMS-omsPro

removeBuyerDetailChannels = shopee