mongo.inventory.uri = ENC(p3TfifT2Lj3n8mxi6e1iaP9D7DgZmBXwHjBE/ez982GlcjHE3nsSWXNOV+Iby2pYHfIAu4K6jvu1+LAORi1T3pixKFdjum5d3ZV4qiwMGJq/zM7NJ9Yyaw==)
mongo.inventory.database = heroku_app20901983

rabbitmq.host = trapped-scabious-54.bigwig.lshift.net
rabbitmq.rx.port = 10447
rabbitmq.tx.port = 10446
rabbitmq.username = ZclP14tC
rabbitmq.password = ENC(KXSjWrUPNrYOZ3Xhj3lNGBax27k5Bb7WNWgSCm3rYzviAWGrldtOZS9M2+anW3PA)
rabbitmq.virtualHost = YB9C-ZD5tFDV

amazonmq.host = angry-scabious-55.bigwig.lshift.net
amazonmq.rx.port = 10889
amazonmq.tx.port = 10888
amazonmq.username = NQJoN0pO
amazonmq.password = ENC(QDUqazFQa4hxtu8sE9evvv7BUyeLkW9RDiq+ZTlQ2oZtOz/yv8S8v9Q0WDg90wPc)
amazonmq.virtualHost = qt8ArOKBG66I

ebaymq.host = trapped-betony-46.bigwig.lshift.net
ebaymq.rx.port = 10033
ebaymq.tx.port = 10032
ebaymq.username = eEYIpQ0S
ebaymq.password = ENC(G0kPUS+pAb/4ilHQ4imxHjj5kj2ljzNWLLTFzv5WFL7VXMNur6FNaF/kGP7UY35B)
ebaymq.virtualHost = vANlK4fNvo0I

shopifymq.host = leaping-laburnum-52.bigwig.lshift.net
shopifymq.rx.port = 10257
shopifymq.tx.port = 10256
shopifymq.username = c5qAMxpv
shopifymq.password = ENC(aER741KwE/xi6+lFOz1NfPeSSCAwIXqO9W76+GpwQObcqrBgsJfnKD9eV4qDrwe6)
shopifymq.virtualHost = ep05BkOkuWkc

sellinallmq.host = energetic-orchis-55.bigwig.lshift.net
sellinallmq.rx.port = 11057
sellinallmq.tx.port = 11056
sellinallmq.username = CtHt9zYm
sellinallmq.password = ENC(4QuqOmm57qbaDNxnCIXhzXYWn+iPsL9ALAqgRxX9v8rzch/HwFItDa0IUOFkz59k)
sellinallmq.virtualHost = s40zhW8jpft8

flipkartmq.host = hungry-violet-45.bigwig.lshift.net
flipkartmq.rx.port = 10079
flipkartmq.tx.port = 10078
flipkartmq.username = 9iYGRxr0
flipkartmq.password = ENC(5pzx3Izwx2mpCYcbU4Y7BtExygR+osANk20Tx+4uaYhRtGiYXCPZe9i2bNBRDgdS)
flipkartmq.virtualHost = PsTRo9M_AS8l

shopcluesmq.host = sad-vilthuril-67.bigwig.lshift.net
shopcluesmq.rx.port = 10329
shopcluesmq.tx.port = 10328
shopcluesmq.username = 6KlV5IJW
shopcluesmq.password = ENC(cffWYsliAS7rYvr/t2IjRJ+99CNt8WuiOQacooTIudULWdzGvIctlPn55Z/81cg2)
shopcluesmq.virtualHost = lNlyQUkRGSpU

etsymq.host = energetic-nildro-hain-67.bigwig.lshift.net
etsymq.rx.port = 11119
etsymq.tx.port = 11118
etsymq.username = fK_L5ln8
etsymq.password = ENC(irmVTGe7ySY6LtDqEc5Mz7Kp240eF5JY6T/fcbKSyQwIkVcDv4FMYac5QAyu2kCg)
etsymq.virtualHost = zp-X4nm89N0y

shopcluesmq.host = sad-vilthuril-67.bigwig.lshift.net
shopcluesmq.rx.port = 10329
shopcluesmq.tx.port = 10328
shopcluesmq.username = 6KlV5IJW
#need to encrypt password
shopcluesmq.password = lZe2KHE6MKWTkh4o8iBJK2ZaMSKRUrSS
shopcluesmq.virtualHost = lNlyQUkRGSpU

#Activity Log
activity.host = furry-speedwell-39.bigwig.lshift.net
activity.port = 10413
activity.username = fXCqH_xq
activity.password = ENC(Zf368a/JubSHQ7nD1uaDu7GV4qxfS99G7Zf7d+cPdInKIu/+H6c5OyUPF4uDSC1t)
activity.virtualHost = 3zvScMyYEWpx

feemanagementmq.host = big-silver-21.bigwig.lshift.net
feemanagementmq.rx.port = 10407
feemanagementmq.tx.port = 10406
feemanagementmq.username = 6NXSFa3u
feemanagementmq.password = ENC(/EJxEPRQRmUiWSkXFgcaRW2ZBe2SsSIWVHcm6d+bMu8EUeyTYH9eJHsZTUnON/ox)
feemanagementmq.virtualHost = 3509FoVkQP72

#userMessagingServer Server URL
userMessaging.host = digging-thethuthinnang-59.bigwig.lshift.net
userMessaging.rx.port = 10053
userMessaging.tx.port = 10052
userMessaging.username = yIZpcrA2
userMessaging.password = ENC(fNyC68Wk4c+LuGk0eH8UHSknQxJfOvl04cNgQk7wLIl/EPxVjT5YUzf/Galiqqpw)
userMessaging.virtualHost = XuOztiGjOmxv

batchProcessor.host = trapped-dandelion-50.bigwig.lshift.net
batchProcessor.tx.port = 10724
batchProcessor.rx.port = 10725
batchProcessor.username = Gab-faT7
batchProcessor.password = ENC(QSRtaBdaxNF0QwxdRDV/n75oTHSY+EoHUWCbDE/t17H5xXt3Yc/WV0OhEyevp0Wb)
batchProcessor.virtualHost = Lw68cAZOQSym
