#Using Mudra Token get Facebook Long Token
FbTokenExchangeUri=ENC(4nKwYhD6+rmZq7yRAtNjAYeSPi7uVNVklANFWVkHzBIukq8Y78skzGMG3qM2ThU02/ixq5rzE5YBk0O4Tqqb1RKW7NhgQ31YboqlKd0C1dDXEintJvwXKwAKL9QqYnuwpC4cMgZ6KSsgNPSLHZ63ZJ6NSD3wKQJIAXjTa3fG6lDZX/Zkm8GuNCUIYw+tExqN77bIrm98I7RizhlAcpkz+hgQdr8Cb37oh3Ek902bw9w=)

orderConfigDBURI=ENC(HF+prdlvHpHErtBGqeDknP1HOAJzqH/+VQNnGvffdbAtnHDt3LbOIM81s+dviacQIUgWU2NzQBATzGsz2nrkP/i19TJz0vEECw8xPpOOZl/4KeQpRV9drA==)
orderConfigDBName =heroku_app20901983

# User And Auth Collection Details 
userConfigDBURI=ENC(q1Yg5iBwyQohMqhUqcL6pBkLPRuKxiUACNGzmdwL6N9zKQdEZ5Bg9cemfiqrCtcrIbPkTeCclPr2bRP4wNOhkjh9uWwxoj4JCoBXctq7sfogfNTcZFe93g==)
userConfigDBName=heroku_app17575512

# Inventory Collection Details 
inventoryConfigDBURI=ENC(HF+prdlvHpHErtBGqeDknP1HOAJzqH/+VQNnGvffdbAtnHDt3LbOIM81s+dviacQIUgWU2NzQBATzGsz2nrkP/i19TJz0vEECw8xPpOOZl/4KeQpRV9drA==)
inventoryConfigDBName =heroku_app20901983

#image URI
uploadImageUri=http://dev.sellonall.com/uploads/

#Notification Email URL
SIAOrderPageURL=http://gandeevam.sellonall.com/Dash/#orders-sold?id=

#Accounting channels
SIAAccountingChannels = quickBooks

#feeManagementServer exchange URL
SIAfeeManagementServerURL = https://staging-feemanagement.herokuapp.com/services

#inventory Endpoint
SIAInventoryManagementServerURL = https://staging-inventorymanagement.herokuapp.com/services

warehouses = satsaco

#need to remove this flag once whatsApp enabled in SIA
whatsAppEnabled = false