mongo.inventory.uri = ENC(ixlq2jsAPUc5AxMwEXHjLbN9DVFtvVtKSUvzdTT7/2Li/McZutO/0+Z7yct3v4ORzgZRfUYoTAtBtksVaUk9Pza/BZCdV0J0tgG41vt/udSq6O7Bvl1dJg==)
mongo.inventory.database = heroku_app20901983

rabbitmq.host = swift-bartsia-42.bigwig.lshift.net
rabbitmq.rx.port = 10081
rabbitmq.tx.port = 10080
rabbitmq.username = eb69Riix
rabbitmq.password = ENC(NETHIwjYwtN5XFzCJP+sqLgBwSX0rVALyLOKAaCcvTRStKBBaac/Pw1dRqiqvR9s)
rabbitmq.virtualHost = G1vwBZdxXcOT

amazonmq.host = swift-bartsia-42.bigwig.lshift.net
amazonmq.rx.port = 10081
amazonmq.tx.port = 10080
amazonmq.username = eb69Riix
amazonmq.password = ENC(NETHIwjYwtN5XFzCJP+sqLgBwSX0rVALyLOKAaCcvTRStKBBaac/Pw1dRqiqvR9s)
amazonmq.virtualHost = G1vwBZdxXcOT

ebaymq.host = swift-bartsia-42.bigwig.lshift.net
ebaymq.rx.port = 10081
ebaymq.tx.port = 10080
ebaymq.username = eb69Riix
ebaymq.password = ENC(NETHIwjYwtN5XFzCJP+sqLgBwSX0rVALyLOKAaCcvTRStKBBaac/Pw1dRqiqvR9s)
ebaymq.virtualHost = G1vwBZdxXcOT

wishmq.host = swift-bartsia-42.bigwig.lshift.net
wishmq.rx.port = 10081
wishmq.tx.port = 10080
wishmq.username = eb69Riix
wishmq.password = ENC(NETHIwjYwtN5XFzCJP+sqLgBwSX0rVALyLOKAaCcvTRStKBBaac/Pw1dRqiqvR9s)
wishmq.virtualHost = G1vwBZdxXcOT

shopifymq.host = swift-bartsia-42.bigwig.lshift.net
shopifymq.rx.port = 10081
shopifymq.tx.port = 10080
shopifymq.username = eb69Riix
shopifymq.password = ENC(NETHIwjYwtN5XFzCJP+sqLgBwSX0rVALyLOKAaCcvTRStKBBaac/Pw1dRqiqvR9s)
shopifymq.virtualHost = G1vwBZdxXcOT

shopeemq.host = swift-bartsia-42.bigwig.lshift.net
shopeemq.rx.port = 10081
shopeemq.tx.port = 10080
shopeemq.username = eb69Riix
shopeemq.password = ENC(NETHIwjYwtN5XFzCJP+sqLgBwSX0rVALyLOKAaCcvTRStKBBaac/Pw1dRqiqvR9s)
shopeemq.virtualHost = G1vwBZdxXcOT

sellinallmq.host = swift-bartsia-42.bigwig.lshift.net
sellinallmq.rx.port = 10081
sellinallmq.tx.port = 10080
sellinallmq.username = eb69Riix
sellinallmq.password = ENC(NETHIwjYwtN5XFzCJP+sqLgBwSX0rVALyLOKAaCcvTRStKBBaac/Pw1dRqiqvR9s)
sellinallmq.virtualHost = G1vwBZdxXcOT

flipkartmq.host = swift-bartsia-42.bigwig.lshift.net
flipkartmq.rx.port = 10081
flipkartmq.tx.port = 10080
flipkartmq.username = eb69Riix
flipkartmq.password = ENC(NETHIwjYwtN5XFzCJP+sqLgBwSX0rVALyLOKAaCcvTRStKBBaac/Pw1dRqiqvR9s)
flipkartmq.virtualHost = G1vwBZdxXcOT

shopcluesmq.host = swift-bartsia-42.bigwig.lshift.net
shopcluesmq.rx.port = 10081
shopcluesmq.tx.port = 10080
shopcluesmq.username = eb69Riix
shopcluesmq.password = ENC(NETHIwjYwtN5XFzCJP+sqLgBwSX0rVALyLOKAaCcvTRStKBBaac/Pw1dRqiqvR9s)
shopcluesmq.virtualHost = G1vwBZdxXcOT

etsymq.host = swift-bartsia-42.bigwig.lshift.net
etsymq.rx.port = 10081
etsymq.tx.port = 10080
etsymq.username = eb69Riix
etsymq.password = ENC(NETHIwjYwtN5XFzCJP+sqLgBwSX0rVALyLOKAaCcvTRStKBBaac/Pw1dRqiqvR9s)
etsymq.virtualHost = G1vwBZdxXcOT

#Activity Log
activity.host = furry-speedwell-39.bigwig.lshift.net
activity.port = 10413
activity.username = fXCqH_xq
activity.password = ENC(Zf368a/JubSHQ7nD1uaDu7GV4qxfS99G7Zf7d+cPdInKIu/+H6c5OyUPF4uDSC1t)
activity.virtualHost = 3zvScMyYEWpx

feemanagementmq.host = big-silver-21.bigwig.lshift.net
feemanagementmq.rx.port = 10407
feemanagementmq.tx.port = 10406
feemanagementmq.username = 6NXSFa3u
feemanagementmq.password = ENC(/EJxEPRQRmUiWSkXFgcaRW2ZBe2SsSIWVHcm6d+bMu8EUeyTYH9eJHsZTUnON/ox)
feemanagementmq.virtualHost = 3509FoVkQP72

#userMessagingServer Server URL
userMessaging.host = digging-thethuthinnang-59.bigwig.lshift.net
userMessaging.rx.port = 10053
userMessaging.tx.port = 10052
userMessaging.username = yIZpcrA2
userMessaging.password = ENC(fNyC68Wk4c+LuGk0eH8UHSknQxJfOvl04cNgQk7wLIl/EPxVjT5YUzf/Galiqqpw)
userMessaging.virtualHost = XuOztiGjOmxv

batchProcessor.host = swift-bartsia-42.bigwig.lshift.net
batchProcessor.tx.port = 10080
batchProcessor.rx.port = 10081
batchProcessor.username = eb69Riix
batchProcessor.password = ENC(NETHIwjYwtN5XFzCJP+sqLgBwSX0rVALyLOKAaCcvTRStKBBaac/Pw1dRqiqvR9s)
batchProcessor.virtualHost = G1vwBZdxXcOT

qoo10mq.host = swift-bartsia-42.bigwig.lshift.net
qoo10mq.rx.port = 10081
qoo10mq.tx.port = 10080
qoo10mq.username = eb69Riix
qoo10mq.password = ENC(NETHIwjYwtN5XFzCJP+sqLgBwSX0rVALyLOKAaCcvTRStKBBaac/Pw1dRqiqvR9s)
qoo10mq.virtualHost = G1vwBZdxXcOT

lazada.host = swift-bartsia-42.bigwig.lshift.net
lazada.rx.port = 10081
lazada.tx.port = 10080
lazada.username = eb69Riix
lazada.password = ENC(NETHIwjYwtN5XFzCJP+sqLgBwSX0rVALyLOKAaCcvTRStKBBaac/Pw1dRqiqvR9s)
lazada.virtualHost = G1vwBZdxXcOT

quickBooks.host = swift-bartsia-42.bigwig.lshift.net
quickBooks.rx.port = 10081
quickBooks.tx.port = 10080
quickBooks.username = eb69Riix
quickBooks.password = ENC(NETHIwjYwtN5XFzCJP+sqLgBwSX0rVALyLOKAaCcvTRStKBBaac/Pw1dRqiqvR9s)
quickBooks.virtualHost = G1vwBZdxXcOT

ninjaVan.host = swift-bartsia-42.bigwig.lshift.net
ninjaVan.rx.port = 10081
ninjaVan.tx.port = 10080
ninjaVan.username = eb69Riix
ninjaVan.password = ENC(NETHIwjYwtN5XFzCJP+sqLgBwSX0rVALyLOKAaCcvTRStKBBaac/Pw1dRqiqvR9s)
ninjaVan.virtualHost = G1vwBZdxXcOT

infor.host = swift-bartsia-42.bigwig.lshift.net
infor.rx.port = 10081
infor.tx.port = 10080
infor.username = eb69Riix
infor.password = ENC(NETHIwjYwtN5XFzCJP+sqLgBwSX0rVALyLOKAaCcvTRStKBBaac/Pw1dRqiqvR9s)
infor.virtualHost = G1vwBZdxXcOT

magentomq.host = swift-bartsia-42.bigwig.lshift.net
magentomq.rx.port = 10081
magentomq.tx.port = 10080
magentomq.username = eb69Riix
magentomq.password = ENC(NETHIwjYwtN5XFzCJP+sqLgBwSX0rVALyLOKAaCcvTRStKBBaac/Pw1dRqiqvR9s)
magentomq.virtualHost = G1vwBZdxXcOT
