#Using Mudra Token get Facebook Long Token
FbTokenExchangeUri=ENC(4nKwYhD6+rmZq7yRAtNjAYeSPi7uVNVklANFWVkHzBIukq8Y78skzGMG3qM2ThU02/ixq5rzE5YBk0O4Tqqb1RKW7NhgQ31YboqlKd0C1dDXEintJvwXKwAKL9QqYnuwpC4cMgZ6KSsgNPSLHZ63ZJ6NSD3wKQJIAXjTa3fG6lDZX/Zkm8GuNCUIYw+tExqN77bIrm98I7RizhlAcpkz+hgQdr8Cb37oh3Ek902bw9w=)

# Mongo Db 

DbUserName=shinmudra
DbPassword=ENC(Rfr42qQpr7oq/Cdbh1JMr1JPpZTy51dY)

# User And Auth Collection Details 

UserCollectionHostName=ds027769.mongolab.com
UserCollectionPort=27769
UserCollectionDBName=heroku_app17575512

# Inventory Collection Details 

InventoryCollectionHostName=ds027729.mongolab.com
InventoryCollectionPort=27729
InventoryCollectionDBName=heroku_app20901983

#image URI
uploadImageUri=http://dev.sellonall.com/uploads/

#Notification Email URL
SIAOrderPageURL=http://dev.sellonall.com/Dash/#orders?id=