package com.sellinall.order.enums;

public enum NotificationOrderActionStatus {
	NO_ACTION("NO_ACTION"), /* No Action */
	INITIATED("INITIATED "), /* "decrement" inventory inStock quantity */
	ACCEPTED("ACCEPTED"), /* "decrement" inventory inStock quantity */
	PROCESSING("PROCESSING"), /* "decrement" inventory inStock quantity */
	DISPATCHED("DISPATCHED "), /* "decrement" inventory inStock quantity */
	DELIVERED("DELIVERED"), /* "decrement" inventory inStock quantity */
	DELIVERY_FAILED("DELIVERY_FAILED"), /* "decrement" inventory inStock quantity */
	CANCELLED("CANCELLED"), /* "increment" inventory inStock quantity */
	CANCEL_PENDING ("CANCEL_PENDING"), /* order cancellation is pending */
	CANCEL_REQUESTED ("CANCEL_REQUESTED"), /* order cancellation is requested */
	RETURNED("RETURNED"),
	COMBINED("COMBINED"), /* No Action, as the sync have happened already */

	INITIATED_TO_ACCEPTED("INITIATED_TO_ACCEPTED"), /* No Action */
	INITIATED_TO_COMBINED("INITIATED_TO_COMBINED"), /* No Action */
	INITIATED_TO_PROCESSING("INITIATED_TO_PROCESSING"), /* No Action */
	INITIATED_TO_DISPATCHED("INITIATED_TO_DISPATCHED"), /* No Action */
	INITIATED_TO_DELIVERED("INITIATED_TO_DELIVERED"), /* No Action */
	ACCEPTED_TO_PROCESSING("ACCEPTED_TO_PROCESSING"), /* No Action */
	ACCEPTED_TO_DISPATCHED("ACCEPTED_TO_DISPATCHED"), /* No Action */
	ACCEPTED_TO_COMBINED("ACCEPTED_TO_COMBINED"), /* No Action */
	ACCEPTED_TO_DELIVERED("ACCEPTED_TO_DELIVERED"), /* No Action */
	PROCESSING_TO_INITIATED("PROCESSING_TO_INITIATED"), /* No Action */
	PROCESSING_TO_DISPATCHED("PROCESSING_TO_DISPATCHED"), /* No Action */
	CANCEL_REQUESTED_TO_DISPATCHED("CANCEL_REQUESTED_TO_DISPATCHED"), /* No Action */
	PROCESSING_TO_DELIVERED("PROCESSING_TO_DELIVERED"), /* No Action */
	PROCESSING_TO_COMBINED("PROCESSING_TO_COMBINED"), /* No Action */
	COMBINED_TO_DISPATCHED("COMBINED_TO_DISPATCHED"), /* No Action */
	DISPATCHED_TO_DELIVERED("DISPATCHED_TO_DELIVERED"), /* No Action */
	CANCEL_REQUESTED_TO_DELIVERED("CANCEL_REQUESTED_TO_DELIVERED"), /* No Action */
	DELIVERY_FAILED_TO_DELIVERED("DELIVERY_FAILED_TO_DELIVERED"), /* No Action */
	DISPATCHED_TO_DELIVERY_FAILED("DISPATCHED_TO_DELIVERY_FAILED"), /* No Action */
	DELIVERED_TO_DISPATCHED("DELIVERED_TO_DISPATCHED"), /* No Action */
	DISPATCHED_TO_PROCESSING("DISPATCHED_TO_PROCESSING"), /* No Action */
	DISPATCHED_TO_CANCELLED("DISPATCHED_TO_CANCELLED"), /* No Action */

	INITIATED_TO_CANCELLED("INITIATED_TO_CANCELLED"), /* "increment" inventory inStock quantity */
	INITIATED_TO_CANCEL_PENDING("INITIATED_TO_CANCEL_PENDING"),
	INITIATED_TO_CANCEL_REQUESTED("INITIATED_TO_CANCEL_REQUESTED"),
	ACCEPTED_TO_CANCELLED("ACCEPTED_TO_CANCELLED"), /* "increment" inventory inStock quantity */
	ACCEPTED_TO_CANCEL_PENDING("ACCEPTED_TO_CANCEL_PENDING"),
	ACCEPTED_TO_CANCEL_REQUESTED("ACCEPTED_TO_CANCEL_REQUESTED"),
	DISPATCHED_TO_RETURNED("DISPATCHED_TO_RETURNED"), /* "increment" inventory inStock quantity */
	DELIVERED_TO_RETURNED("DELIVERED_TO_RETURNED"), /* "increment" inventory inStock quantity */
	PROCESSING_TO_CANCELLED("PROCESSING_TO_CANCELLED"), /* "increment" inventory inStock quantity */
	DELIVERED_TO_CANCELLED("DELIVERED_TO_CANCELLED"),
	
	PROCESSING_TO_RETURNED("PROCESSING_TO_RETURNED"),
	CANCEL_REQUESTED_TO_ACCEPTED("CANCEL_REQUESTED_TO_ACCEPTED"),
	DELIVERED_TO_DELIVERY_FAILED("DELIVERED_TO_DELIVERY_FAILED"),
	
	CANCEL_PENDING_TO_CANCELLED("CANCEL_PENDING_TO_CANCELLED"),
	CANCEL_REQUESTED_TO_CANCELLED("CANCEL_REQUESTED_TO_CANCELLED"),
	CANCEL_REQUESTED_TO_INITIATED("CANCEL_REQUESTED_TO_INITIATED");

	private final String name;

	private NotificationOrderActionStatus(String s) {
		name = s;
	}

	public boolean equalsName(String otherName) {
		return (otherName == null) ? false : name.equals(otherName);
	}

	public String toString() {
		return this.name;
	}

}